### ISSUE TITLE
Is the pth model converted from the tensorflow version?

### ISSUE THREAD

**Issue by skanderbug** [changhongjian/Deep3DFaceReconstruction-pytorch#1]
Thanks for your project. It's really helpful.
I find you have implemented a fast auto-diff renderer. So, is this model converted from the tensorflow version or you trained from pytorch?

**Comment by changhongjian** [comment]
I converted it from the tensorflow model. Sorry for the late reply.

**Comment by skanderbug** [comment]
Got it. Thank you all the same!
